language: node_js

addons:
  apt:
    packages:
      - xvfb

before_install:
  - "npm install -g npm@3"

node_js:
  - "6"
  - "7"

notifications:
  email: false

install:
  - npm i
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &